/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.mydsl1.aDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>For2 Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl1.aDSL.For2Statement#getPar <em>Par</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.aDSL.For2Statement#getData <em>Data</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.aDSL.For2Statement#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl1.aDSL.ADSLPackage#getFor2Statement()
 * @model
 * @generated
 */
public interface For2Statement extends Statement
{
  /**
   * Returns the value of the '<em><b>Par</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Par</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Par</em>' containment reference.
   * @see #setPar(Parameter)
   * @see org.xtext.example.mydsl1.aDSL.ADSLPackage#getFor2Statement_Par()
   * @model containment="true"
   * @generated
   */
  Parameter getPar();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.aDSL.For2Statement#getPar <em>Par</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Par</em>' containment reference.
   * @see #getPar()
   * @generated
   */
  void setPar(Parameter value);

  /**
   * Returns the value of the '<em><b>Data</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Data</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data</em>' containment reference.
   * @see #setData(Expression)
   * @see org.xtext.example.mydsl1.aDSL.ADSLPackage#getFor2Statement_Data()
   * @model containment="true"
   * @generated
   */
  Expression getData();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.aDSL.For2Statement#getData <em>Data</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Data</em>' containment reference.
   * @see #getData()
   * @generated
   */
  void setData(Expression value);

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Body</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(Block)
   * @see org.xtext.example.mydsl1.aDSL.ADSLPackage#getFor2Statement_Body()
   * @model containment="true"
   * @generated
   */
  Block getBody();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.aDSL.For2Statement#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(Block value);

} // For2Statement
