/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.mydsl1.aDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>For Stat</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl1.aDSL.ForStat#getTemp <em>Temp</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.aDSL.ForStat#getCondition <em>Condition</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.aDSL.ForStat#getFinalexp <em>Finalexp</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.aDSL.ForStat#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl1.aDSL.ADSLPackage#getForStat()
 * @model
 * @generated
 */
public interface ForStat extends Statement
{
  /**
   * Returns the value of the '<em><b>Temp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Temp</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Temp</em>' containment reference.
   * @see #setTemp(VariableDef)
   * @see org.xtext.example.mydsl1.aDSL.ADSLPackage#getForStat_Temp()
   * @model containment="true"
   * @generated
   */
  VariableDef getTemp();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.aDSL.ForStat#getTemp <em>Temp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Temp</em>' containment reference.
   * @see #getTemp()
   * @generated
   */
  void setTemp(VariableDef value);

  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Condition</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(Expression)
   * @see org.xtext.example.mydsl1.aDSL.ADSLPackage#getForStat_Condition()
   * @model containment="true"
   * @generated
   */
  Expression getCondition();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.aDSL.ForStat#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(Expression value);

  /**
   * Returns the value of the '<em><b>Finalexp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Finalexp</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Finalexp</em>' containment reference.
   * @see #setFinalexp(Expression)
   * @see org.xtext.example.mydsl1.aDSL.ADSLPackage#getForStat_Finalexp()
   * @model containment="true"
   * @generated
   */
  Expression getFinalexp();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.aDSL.ForStat#getFinalexp <em>Finalexp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Finalexp</em>' containment reference.
   * @see #getFinalexp()
   * @generated
   */
  void setFinalexp(Expression value);

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Body</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(Block)
   * @see org.xtext.example.mydsl1.aDSL.ADSLPackage#getForStat_Body()
   * @model containment="true"
   * @generated
   */
  Block getBody();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.aDSL.ForStat#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(Block value);

} // ForStat
