/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.mydsl1.aDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Int Constant</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl1.aDSL.IntConstant#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl1.aDSL.ADSLPackage#getIntConstant()
 * @model
 * @generated
 */
public interface IntConstant extends Expression
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(IntegerNegative)
   * @see org.xtext.example.mydsl1.aDSL.ADSLPackage#getIntConstant_Value()
   * @model containment="true"
   * @generated
   */
  IntegerNegative getValue();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.aDSL.IntConstant#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(IntegerNegative value);

} // IntConstant
