/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.mydsl1.aDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Member Selection</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl1.aDSL.MemberSelection#getReceiver <em>Receiver</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.aDSL.MemberSelection#getMember <em>Member</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.aDSL.MemberSelection#isIspar <em>Ispar</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.aDSL.MemberSelection#getPar <em>Par</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.aDSL.MemberSelection#isMethodinvocation <em>Methodinvocation</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.aDSL.MemberSelection#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl1.aDSL.ADSLPackage#getMemberSelection()
 * @model
 * @generated
 */
public interface MemberSelection extends Expression
{
  /**
   * Returns the value of the '<em><b>Receiver</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Receiver</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Receiver</em>' containment reference.
   * @see #setReceiver(Expression)
   * @see org.xtext.example.mydsl1.aDSL.ADSLPackage#getMemberSelection_Receiver()
   * @model containment="true"
   * @generated
   */
  Expression getReceiver();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.aDSL.MemberSelection#getReceiver <em>Receiver</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Receiver</em>' containment reference.
   * @see #getReceiver()
   * @generated
   */
  void setReceiver(Expression value);

  /**
   * Returns the value of the '<em><b>Member</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Member</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Member</em>' reference.
   * @see #setMember(Member)
   * @see org.xtext.example.mydsl1.aDSL.ADSLPackage#getMemberSelection_Member()
   * @model
   * @generated
   */
  Member getMember();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.aDSL.MemberSelection#getMember <em>Member</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Member</em>' reference.
   * @see #getMember()
   * @generated
   */
  void setMember(Member value);

  /**
   * Returns the value of the '<em><b>Ispar</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ispar</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ispar</em>' attribute.
   * @see #setIspar(boolean)
   * @see org.xtext.example.mydsl1.aDSL.ADSLPackage#getMemberSelection_Ispar()
   * @model
   * @generated
   */
  boolean isIspar();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.aDSL.MemberSelection#isIspar <em>Ispar</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ispar</em>' attribute.
   * @see #isIspar()
   * @generated
   */
  void setIspar(boolean value);

  /**
   * Returns the value of the '<em><b>Par</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Par</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Par</em>' reference.
   * @see #setPar(XClass)
   * @see org.xtext.example.mydsl1.aDSL.ADSLPackage#getMemberSelection_Par()
   * @model
   * @generated
   */
  XClass getPar();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.aDSL.MemberSelection#getPar <em>Par</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Par</em>' reference.
   * @see #getPar()
   * @generated
   */
  void setPar(XClass value);

  /**
   * Returns the value of the '<em><b>Methodinvocation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Methodinvocation</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Methodinvocation</em>' attribute.
   * @see #setMethodinvocation(boolean)
   * @see org.xtext.example.mydsl1.aDSL.ADSLPackage#getMemberSelection_Methodinvocation()
   * @model
   * @generated
   */
  boolean isMethodinvocation();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.aDSL.MemberSelection#isMethodinvocation <em>Methodinvocation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Methodinvocation</em>' attribute.
   * @see #isMethodinvocation()
   * @generated
   */
  void setMethodinvocation(boolean value);

  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl1.aDSL.Expression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Args</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference list.
   * @see org.xtext.example.mydsl1.aDSL.ADSLPackage#getMemberSelection_Args()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getArgs();

} // MemberSelection
