/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.mydsl1.aDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Try Catch Stat</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl1.aDSL.TryCatchStat#getBodyTry <em>Body Try</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.aDSL.TryCatchStat#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.aDSL.TryCatchStat#getBodyCatch <em>Body Catch</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl1.aDSL.ADSLPackage#getTryCatchStat()
 * @model
 * @generated
 */
public interface TryCatchStat extends Statement
{
  /**
   * Returns the value of the '<em><b>Body Try</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Body Try</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body Try</em>' containment reference.
   * @see #setBodyTry(Body)
   * @see org.xtext.example.mydsl1.aDSL.ADSLPackage#getTryCatchStat_BodyTry()
   * @model containment="true"
   * @generated
   */
  Body getBodyTry();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.aDSL.TryCatchStat#getBodyTry <em>Body Try</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body Try</em>' containment reference.
   * @see #getBodyTry()
   * @generated
   */
  void setBodyTry(Body value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl1.aDSL.ADSLPackage#getTryCatchStat_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.aDSL.TryCatchStat#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Body Catch</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Body Catch</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body Catch</em>' containment reference.
   * @see #setBodyCatch(Body)
   * @see org.xtext.example.mydsl1.aDSL.ADSLPackage#getTryCatchStat_BodyCatch()
   * @model containment="true"
   * @generated
   */
  Body getBodyCatch();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.aDSL.TryCatchStat#getBodyCatch <em>Body Catch</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body Catch</em>' containment reference.
   * @see #getBodyCatch()
   * @generated
   */
  void setBodyCatch(Body value);

} // TryCatchStat
