/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.mydsl1;

import com.google.inject.Binder;
import com.google.inject.binder.AnnotatedBindingBuilder;
import com.google.inject.binder.LinkedBindingBuilder;
import com.google.inject.name.Named;
import com.google.inject.name.Names;
import org.eclipse.xtext.resource.IDefaultResourceDescriptionStrategy;
import org.eclipse.xtext.scoping.IScopeProvider;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;
import org.xtext.example.mydsl1.AbstractADSLRuntimeModule;
import org.xtext.example.mydsl1.scoping.ADSLImportedNamespaceAwareLocalScopeProvider;
import org.xtext.example.mydsl1.scoping.ADSLResourceDescriptionsStrategy;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ADSLRuntimeModule extends AbstractADSLRuntimeModule {
  @Override
  public void configureIScopeProviderDelegate(final Binder binder) {
    AnnotatedBindingBuilder<IScopeProvider> _bind = binder.<IScopeProvider>bind(IScopeProvider.class);
    Named _named = Names.named(AbstractDeclarativeScopeProvider.NAMED_DELEGATE);
    LinkedBindingBuilder<IScopeProvider> _annotatedWith = _bind.annotatedWith(_named);
    _annotatedWith.to(ADSLImportedNamespaceAwareLocalScopeProvider.class);
  }
  
  public Class<? extends IDefaultResourceDescriptionStrategy> bindIDefaultResourceDescriptionStrategy() {
    return ADSLResourceDescriptionsStrategy.class;
  }
}
