/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.mydsl1;

import org.xtext.example.mydsl1.ADSLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ADSLStandaloneSetup extends ADSLStandaloneSetupGenerated {
  public static void doSetup() {
    ADSLStandaloneSetup _aDSLStandaloneSetup = new ADSLStandaloneSetup();
    _aDSLStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
