/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.mydsl1.aDSL.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl1.aDSL.ADSLPackage;
import org.xtext.example.mydsl1.aDSL.Here;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Here</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class HereImpl extends ExpressionImpl implements Here
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected HereImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ADSLPackage.Literals.HERE;
  }

} //HereImpl
