/**
 * generated by Xtext 2.9.0
 */
package org.xtext.example.mydsl1.aDSL.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl1.aDSL.ADSLPackage;
import org.xtext.example.mydsl1.aDSL.Expression;
import org.xtext.example.mydsl1.aDSL.Member;
import org.xtext.example.mydsl1.aDSL.MemberSelection;
import org.xtext.example.mydsl1.aDSL.XClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Member Selection</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl1.aDSL.impl.MemberSelectionImpl#getReceiver <em>Receiver</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.aDSL.impl.MemberSelectionImpl#getMember <em>Member</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.aDSL.impl.MemberSelectionImpl#isIspar <em>Ispar</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.aDSL.impl.MemberSelectionImpl#getPar <em>Par</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.aDSL.impl.MemberSelectionImpl#isMethodinvocation <em>Methodinvocation</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.aDSL.impl.MemberSelectionImpl#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MemberSelectionImpl extends ExpressionImpl implements MemberSelection
{
  /**
   * The cached value of the '{@link #getReceiver() <em>Receiver</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReceiver()
   * @generated
   * @ordered
   */
  protected Expression receiver;

  /**
   * The cached value of the '{@link #getMember() <em>Member</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMember()
   * @generated
   * @ordered
   */
  protected Member member;

  /**
   * The default value of the '{@link #isIspar() <em>Ispar</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIspar()
   * @generated
   * @ordered
   */
  protected static final boolean ISPAR_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIspar() <em>Ispar</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIspar()
   * @generated
   * @ordered
   */
  protected boolean ispar = ISPAR_EDEFAULT;

  /**
   * The cached value of the '{@link #getPar() <em>Par</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPar()
   * @generated
   * @ordered
   */
  protected XClass par;

  /**
   * The default value of the '{@link #isMethodinvocation() <em>Methodinvocation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isMethodinvocation()
   * @generated
   * @ordered
   */
  protected static final boolean METHODINVOCATION_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isMethodinvocation() <em>Methodinvocation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isMethodinvocation()
   * @generated
   * @ordered
   */
  protected boolean methodinvocation = METHODINVOCATION_EDEFAULT;

  /**
   * The cached value of the '{@link #getArgs() <em>Args</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArgs()
   * @generated
   * @ordered
   */
  protected EList<Expression> args;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MemberSelectionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ADSLPackage.Literals.MEMBER_SELECTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Expression getReceiver()
  {
    return receiver;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetReceiver(Expression newReceiver, NotificationChain msgs)
  {
    Expression oldReceiver = receiver;
    receiver = newReceiver;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ADSLPackage.MEMBER_SELECTION__RECEIVER, oldReceiver, newReceiver);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setReceiver(Expression newReceiver)
  {
    if (newReceiver != receiver)
    {
      NotificationChain msgs = null;
      if (receiver != null)
        msgs = ((InternalEObject)receiver).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ADSLPackage.MEMBER_SELECTION__RECEIVER, null, msgs);
      if (newReceiver != null)
        msgs = ((InternalEObject)newReceiver).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ADSLPackage.MEMBER_SELECTION__RECEIVER, null, msgs);
      msgs = basicSetReceiver(newReceiver, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ADSLPackage.MEMBER_SELECTION__RECEIVER, newReceiver, newReceiver));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Member getMember()
  {
    if (member != null && member.eIsProxy())
    {
      InternalEObject oldMember = (InternalEObject)member;
      member = (Member)eResolveProxy(oldMember);
      if (member != oldMember)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, ADSLPackage.MEMBER_SELECTION__MEMBER, oldMember, member));
      }
    }
    return member;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Member basicGetMember()
  {
    return member;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setMember(Member newMember)
  {
    Member oldMember = member;
    member = newMember;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ADSLPackage.MEMBER_SELECTION__MEMBER, oldMember, member));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isIspar()
  {
    return ispar;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIspar(boolean newIspar)
  {
    boolean oldIspar = ispar;
    ispar = newIspar;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ADSLPackage.MEMBER_SELECTION__ISPAR, oldIspar, ispar));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public XClass getPar()
  {
    if (par != null && par.eIsProxy())
    {
      InternalEObject oldPar = (InternalEObject)par;
      par = (XClass)eResolveProxy(oldPar);
      if (par != oldPar)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, ADSLPackage.MEMBER_SELECTION__PAR, oldPar, par));
      }
    }
    return par;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public XClass basicGetPar()
  {
    return par;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPar(XClass newPar)
  {
    XClass oldPar = par;
    par = newPar;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ADSLPackage.MEMBER_SELECTION__PAR, oldPar, par));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isMethodinvocation()
  {
    return methodinvocation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setMethodinvocation(boolean newMethodinvocation)
  {
    boolean oldMethodinvocation = methodinvocation;
    methodinvocation = newMethodinvocation;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ADSLPackage.MEMBER_SELECTION__METHODINVOCATION, oldMethodinvocation, methodinvocation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Expression> getArgs()
  {
    if (args == null)
    {
      args = new EObjectContainmentEList<Expression>(Expression.class, this, ADSLPackage.MEMBER_SELECTION__ARGS);
    }
    return args;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ADSLPackage.MEMBER_SELECTION__RECEIVER:
        return basicSetReceiver(null, msgs);
      case ADSLPackage.MEMBER_SELECTION__ARGS:
        return ((InternalEList<?>)getArgs()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ADSLPackage.MEMBER_SELECTION__RECEIVER:
        return getReceiver();
      case ADSLPackage.MEMBER_SELECTION__MEMBER:
        if (resolve) return getMember();
        return basicGetMember();
      case ADSLPackage.MEMBER_SELECTION__ISPAR:
        return isIspar();
      case ADSLPackage.MEMBER_SELECTION__PAR:
        if (resolve) return getPar();
        return basicGetPar();
      case ADSLPackage.MEMBER_SELECTION__METHODINVOCATION:
        return isMethodinvocation();
      case ADSLPackage.MEMBER_SELECTION__ARGS:
        return getArgs();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ADSLPackage.MEMBER_SELECTION__RECEIVER:
        setReceiver((Expression)newValue);
        return;
      case ADSLPackage.MEMBER_SELECTION__MEMBER:
        setMember((Member)newValue);
        return;
      case ADSLPackage.MEMBER_SELECTION__ISPAR:
        setIspar((Boolean)newValue);
        return;
      case ADSLPackage.MEMBER_SELECTION__PAR:
        setPar((XClass)newValue);
        return;
      case ADSLPackage.MEMBER_SELECTION__METHODINVOCATION:
        setMethodinvocation((Boolean)newValue);
        return;
      case ADSLPackage.MEMBER_SELECTION__ARGS:
        getArgs().clear();
        getArgs().addAll((Collection<? extends Expression>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ADSLPackage.MEMBER_SELECTION__RECEIVER:
        setReceiver((Expression)null);
        return;
      case ADSLPackage.MEMBER_SELECTION__MEMBER:
        setMember((Member)null);
        return;
      case ADSLPackage.MEMBER_SELECTION__ISPAR:
        setIspar(ISPAR_EDEFAULT);
        return;
      case ADSLPackage.MEMBER_SELECTION__PAR:
        setPar((XClass)null);
        return;
      case ADSLPackage.MEMBER_SELECTION__METHODINVOCATION:
        setMethodinvocation(METHODINVOCATION_EDEFAULT);
        return;
      case ADSLPackage.MEMBER_SELECTION__ARGS:
        getArgs().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ADSLPackage.MEMBER_SELECTION__RECEIVER:
        return receiver != null;
      case ADSLPackage.MEMBER_SELECTION__MEMBER:
        return member != null;
      case ADSLPackage.MEMBER_SELECTION__ISPAR:
        return ispar != ISPAR_EDEFAULT;
      case ADSLPackage.MEMBER_SELECTION__PAR:
        return par != null;
      case ADSLPackage.MEMBER_SELECTION__METHODINVOCATION:
        return methodinvocation != METHODINVOCATION_EDEFAULT;
      case ADSLPackage.MEMBER_SELECTION__ARGS:
        return args != null && !args.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (ispar: ");
    result.append(ispar);
    result.append(", methodinvocation: ");
    result.append(methodinvocation);
    result.append(')');
    return result.toString();
  }

} //MemberSelectionImpl
