/*
 * generated by Xtext 2.9.0
 */
package org.xtext.example.mydsl1

import org.eclipse.xtext.scoping.IScopeProvider
import org.xtext.example.mydsl1.scoping.ADSLImportedNamespaceAwareLocalScopeProvider
import com.google.inject.name.Names
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider
import com.google.inject.Binder
import org.eclipse.xtext.resource.IDefaultResourceDescriptionStrategy
import org.xtext.example.mydsl1.scoping.ADSLResourceDescriptionsStrategy

//import org.xtext.example.mydsl1.scoping.ADSLResourceDescriptionsStrategy
/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ADSLRuntimeModule extends AbstractADSLRuntimeModule {
	
override configureIScopeProviderDelegate(Binder binder) {
        binder.bind(IScopeProvider)
            .annotatedWith(Names.named(AbstractDeclarativeScopeProvider.NAMED_DELEGATE))
            .to(ADSLImportedNamespaceAwareLocalScopeProvider)
    }	
	
	def Class<? extends IDefaultResourceDescriptionStrategy> bindIDefaultResourceDescriptionStrategy() {
		return ADSLResourceDescriptionsStrategy;
	}	
	
}
 